# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: format
      - task: test
      - task: build

  build:
    desc: Builds app
    cmds:
      - roc build --target wasm32
    sources:
      - main.roc
    generates:
      - main.wasm

  format:
    desc: Formats roc files
    cmds:
      - roc format main.roc tests/
    sources:
      - main.roc
      - tests/*.roc

  test:
    desc: Runs checks and tests
    cmds:
      - roc format --check main.roc tests/
      - roc check
      - roc test
    sources:
      - main.roc
      - tests/*.roc


  get-roc:
    desc: Downloads the latest nightly build of roc and unzips it
    cmds:
      - wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz --output-document roc.tar.gz
      - tar -xf roc.tar.gz
      - rm roc.tar.gz
