# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Builds elm app
    cmds:
      - elm make src/Main.elm --optimize --output elm.js
    sources:
      - src/*.elm
    generates:
      - elm.js
